name: danish CI

on:
  push:
    branches:
      - main
      - releases/*

  pull_request:
    branches:
      - main
      - releases/*

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: ['3.10', '3.11', '3.12', '3.13']
        CC: [ gcc ]
        CXX: [ g++ ]
        include:
          - os: macos-latest
            py: '3.10'
            CC: cc
            CXX: c++
          - os: ubuntu-latest
            py: '3.10'
            CC: clang
            CXX: clang++

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Print github context properties
        run: |
          echo 'event: ${{ github.event_name }}'
          echo 'sha: ${{ github.sha }}'
          echo 'ref: ${{ github.ref }}'
          echo 'head_ref: ${{ github.head_ref }}'
          echo 'base_ref: ${{ github.base_ref }}'
          echo 'event.before: ${{ github.event.before }}'
          echo 'event.after: ${{ github.event.after }}'

      - name: Set up Python ${{ matrix.py }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py }}

      - name: Update pip
        run: python -m pip install -U pip

      - name: Get pip cache dir
        id: pip-cache
        shell: bash
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.py }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.py }}-pip-
              ${{ runner.os }}-

      - name: Install GalSim + batoid
        run: |
          python -m pip install GalSim~=2.7.0 batoid

      - name: Build danish
        run: python -m pip install -e .

      - name: List all installed packages for reference
        run: python -m pip list

      - name: Install test requirements
        run: python -m pip install -U pytest pytest-xdist pytest-cov

      - name: Run unit tests
        run: pytest --cov=danish --cov-report=xml --cov-config tests/.coveragerc

      - name: Upload coverage reports to Codecov
        if: matrix.os == 'macos-latest'
        run: |
          curl -Os https://cli.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml
